name: Daily Fuel Price Update

on:
  schedule:
    # Runs at 00:00 UTC daily. This translates to 5:30 AM IST (Indian Standard Time)
    # due to UTC+5:30 offset. Adjust if you need a different local time.
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow from GitHub UI

jobs:
  update_data:
    runs-on: ubuntu-latest # The type of runner that the job will run on
    permissions:
      contents: write # Grant write permission to the GITHUB_TOKEN for this job

    steps:
    - name: Checkout repository # Step to get your code from the repository
      uses: actions/checkout@v4

    - name: Set up Python # Step to set up the Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Specify the Python version to use

    - name: Install dependencies # Step to install Python packages listed in requirements.txt
      run: pip install -r requirements.txt

    - name: Run data fetch and update script # Execute your Python script to fetch and save data
      run: python fetch_fuel_data.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'Automated daily fuel price update'
        file_pattern: 'fuel_prices.csv'
        commit_user_name: 'github-actions[bot]'
        commit_user_email: 'github-actions[bot]@users.noreply.github.com'
        skip_dirty_check: false